networks:
  networkhospitalmoduleuser:

services:
  sqlserverdocker:
    container_name: sql-server-docker
    image:  mcr.microsoft.com/mssql/server:2019-latest
    ports:
        - 1433:1433
    environment: 
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=Colombia2025*/
    networks:
        - networkhospitalmoduleuser

  hospitalmoduleuser.api:
    image: ${DOCKER_REGISTRY-}hospitalmoduleuser
    build:
      context: .
      dockerfile: HospitalModuleUser.Api/Dockerfile
    networks:
        - networkhospitalmoduleuser
    depends_on:
        - sqlserverdocker
    environment:
      ConnectionStrings__db: "Server=sqlserverdocker;Database=HospitalPracticeDBDocker;User Id=sa;Password=Colombia2025*/;TrustServerCertificate=true"
    ports:
        - 5001:80
